### PR TITLE
adding JonasEndpointNotificationService feature to Bag

### PR DESCRIPTION
**Pull request by Paca**
adding a new class named:"JonasEndpointNotificationService " Implementing "IServiceEndpoinNotificationService" interface to be able to used the webhook and service endpoint with this pluginbase classes that is realy 💯 amazing!

### CODE REVIEW

**Comment by Paca** [comment]
Hello Jonas,
May I ask you to review and merge this feature added.
And also push it on nuget repository will be greathfuly appreciated 👍

**Comment by rappen** [comment]
Thanks for your PR! :)

Could you please send some info about when to use this? A small example?

**Comment by Paca** [comment]
> Thanks for your PR! :)
> 
> Could you please send some info about when to use this? A small example?

You need create a webhook here I used a flow trigger http received as describe in this video : [https://www.youtube.com/watch?v=Jk8CCm0gJ58&ab_channel=MicrosoftDynamics365%26PowerPlatform](https://www.youtube.com/watch?v=Jk8CCm0gJ58&ab_channel=MicrosoftDynamics365%26PowerPlatform)

Here is my example including updated SamplePlugin with class DocumentWebHookConverter :
[FlowDoc - Paca_WebHook-ConvertDocuments.zip](https://github.com/rappen/JonasPluginBase/files/13795016/FlowDoc.-.Paca_WebHook-ConvertDocuments.zip)

If you need more info just tell me ;)

**Comment by rappen** [comment]
Thanks - looks good! :)

**Comment by Paca** [comment]
> Thanks - looks good! :)

Is it possible when you had time to push it on nuget.org gallery package [Rappen.Xrm.JonasPluginBase](https://www.nuget.org/packages/Rappen.Xrm.JonasPluginBase)?

**Comment by rappen** [comment]
Now it's there!

**Comment by Paca** [comment]
> Now it's there!

Thanks you rock ! 👍

**Pull request merged**
